name: CI

on: [push]

jobs:
  nix:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set nix path
        id: nix-path
        run: |
          echo ::set-output name=nixpkgs::$(jq -r .nixpkgs.url ./nix/sources.json)

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=${{ steps.nix-path.outputs.nixpkgs }}
          extra_nix_config: |
            log-lines = 1000

      - uses: cachix/cachix-action@v8
        with:
          name: pwm
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: Install nix-build-uncached
        run: |
          nix-build nix -A nix-build-uncached

      - name: Build
        run: |
          result/bin/nix-build-uncached ./nix/release.nix

      - name: Run
        run: |
          nix-build nix/release.nix
          nix-shell --run "run"
